### ISSUE TITLE
conflict with django-constance app? 

### ISSUE THREAD

**Issue by shtalinberg** [django-admin-tools/django-admin-tools#103] opened 2020-02-06 12:37 UTC
Request Method: | GET
http://localhost:8000/admin/constance/
Django 2.2.10
AttributeError
'Meta' object has no attribute 'concrete_model'

/.venv/3.6.4/lib/python3.6/site-packages/admin_tools/dashboard/dashboards.py in     

def get_app_content_types(self):
        """
        Return a list of all content_types for this app.
        """
        # Import this here to silence RemovedInDjango19Warning. See #15
        from django.contrib.contenttypes.models import ContentType
line 211        return [ContentType.objects.get_for_model(c) for c in self.get_app_model_classes()]

**Comment by yakky** [comment] 2020-02-19 06:02
Confirmed

**Comment by shtalinberg** [comment] 2021-01-12 13:46
https://github.com/jazzband/django-constance/issues/244  related ticket in that app 
 a workaround for admin.py is worked - but maybe this bag  can be resolved without a workaround?

**Comment by izimobil** [comment] 2021-01-12 14:36
I've "fixed" the issue by intercepting the AttributeError, but IMO, this should be fixed on django-constance side because it can happen with other third party apps (see @jezdez comment : https://github.com/jazzband/django-constance/issues/244#issuecomment-346974463)

**Closed by izimobil** 2021-01-12 14:36 UTC
Labels: bug

**Comment by jezdez** [comment] 2021-01-12 15:52
I've opened a PR in django-constance to see if this fixes the issue..
